#!/bin/sh
###########################
# This script is used to manually transfer OFS files from WCOSS onto CO-OPS AWS cloud bucket of s3://co-ops.nceptransfer
# ./Manu_JNOS_OFS_AWS envir OFS YYYYMMDD CYC Platform
# ./Manu_JNOS_OFS_AWS prod cbofs 20210715 06 ptmp
#  envir - prod or dev. prod means transfer operational files from NCO run; "dev" means transfering files from development run
#  OFS - OFS name, e.g. cbofs, dbofs, creofs, etc.
#  YYYYMMDD - date to be transferred
#  CYC - cycle of that day to be transferred
#  Platform - Dell1 or Dell3 for envir=dev; it is a dummy augment if envir=prod;

export PACKAGEROOT=/lfs/h1/nos/nosofs/noscrub/$LOGNAME/packages
. $PACKAGEROOT/nosofs.v3.5.0/versions/run.ver
#. /lfs/h1/nos/nosofs/noscrub/$LOGNAME/packages/nosofs.v3.5.0/versions/run.ver

export DATAROOT=/lfs/h1/nos/ptmp/$LOGNAME/work/${nosofs_ver}/${OFS}
set -xa

module purge
module load envvar/$envvars_ver

# Loading Intel Compiler Suite
module load PrgEnv-intel/${PrgEnv_intel_ver}
module load craype/${craype_ver}
module load intel/${intel_ver}
#module load cray-mpich/${cray_mpich_ver}
module load cray-pals/${cray_pals_ver}
#Set other library variables
#module load libjpeg/${libjpeg_ver}
#module load netcdf/${netcdf_ver}
#module load hdf5/${hdf5_ver}
#module load subversion/${subversion_ver}
#module load python/${python_ver}
module load prod_envir/${prod_envir_ver}
module load prod_util/${prod_util_ver}
#module load grib_util/${grib_util_ver}
module load cfp/${cfp_ver}
#module load nco/${nco_ver}
module load awscli/1.16.308

envir=$1
OFS=$2
PDY=$3
cyc=$4
platform=$5
#PDY=20201218
job="manu_aws"

export DATAROOT=/lfs/h1/nos/${platform}/$LOGNAME/work/${nosofs_ver}/${OFS}
########################################
# NOS_OFS_AWS  for development work only
########################################
export HOMEnos=${HOMEnos:-${PACKAGEROOT}/nosofs.${nosofs_ver:?}}
######################################################
# The following two variable could be defined in the
# loadleveler submission script (the sms script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

###################################
# Specify NET and RUN Name and model
####################################
export OFS=${OFS}
export NET=${NET:-nosofs}
export RUN=${RUN:-$OFS}
export PREFIXNOS=${PREFIXNOS:-nos.$OFS}
export platform=${platform:-H1}
if [ $envir == "dev" ]; then
  export COMROOT=${COMROOT:-/lfs/h1/nos/${platform}/$LOGNAME/com}
  export COMOUTroot=${COMOUTroot:-${COMROOT}/${NET}/${nosofs_ver:0:4}}       # output directory
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${nosofs_ver:0:4}/${RUN}.${PDY}}  # output directory
  export DATAROOT=/lfs/h1/nos/${platform}/$LOGNAME/work/${nosofs_ver}/${OFS}
else
   export COMOUTroot=/lfs/h1/ops/prod/com/
   export DATAROOT=/gpfs/${platform,,}/ptmp/$LOGNAME/${OFS}/work_aws
   export DATAROOT=/lfs/h1/nos/${platform}/$LOGNAME/work/${nosofs_ver}/${OFS}
fi

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
export COMROOT=${COMROOT:-/lfs/h1/ops/prod/com}
export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/prod/dcom}

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATAROOT=${DATAROOT:-/lfs/h1/ops/prod/tmp}
#export DATA=${DATA:-$DATAROOT/${job}.${pid}}
export DATA=${DATA:-${DATAROOT:?}/nos_${OFS}_aws_${cyc}_$envir}
#if [ $envir = prod ]; then
#  rm -rf ${DATAROOT}/*
#fi
if [ ! -d $DATA ]
then
  mkdir -p $DATA
  cd $DATA
else
  cd $DATA
  rm -fr $DATA/*
fi
export cycle=t${cyc}z

############################################
#   Determine Job Output Name on System
############################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# Specify Execution Areas
####################################
export EXECnos=${EXECnos:-${HOMEnos}/exec}
export PARMnos=${PARMnos:-${HOMEnos}/parm}
export USHnos=${USHnos:-${HOMEnos}/ush}
export SCRIPTSnos=${SCRIPTSnos:-${HOMEnos}/scripts}
export FIXnos=${FIXnos:-${HOMEnos}/fix/shared}
export FIXofs=${FIXofs:-${HOMEnos}/fix/${OFS}}

###########################################
# Run setpdy and initialize PDY variables
###########################################
#sh setpdy.sh
#. ./PDY
#export PDY=20210824
##############################################
# Define COM directories
##############################################

#export COMIN=${COMIN:-${COMROOT}/${NET}/${nosofs_ver:0:4}/${RUN}.${PDY}}   # input directory
#export COMOUTroot=${COMOUTroot:-${COMROOT}/${NET}/${nosofs_ver:0:4}}       # output directory
#export COMOUT=${COMOUT:-${COMROOT}/${NET}/${nosofs_ver:0:4}/${RUN}.${PDY}}  # output directory

if [ $envir == "dev" ]; then
    export COMROOT=/lfs/h1/nos/ptmp/$LOGNAME/com
    export COMOUTroot=${COMOUTroot:-${COMROOT}/${NET}/${nosofs_ver:0:4}}       # output directory
    export COMOUT=${COMOUT:-${COMROOT}/${NET}/${nosofs_ver:0:4}/${RUN}.${PDY}}  # output directory
elif [ $envir == "prod" ]; then
    export COMROOT=/lfs/h1/ops/prod/com
    export COMOUTroot=${COMOUTroot:-${COMROOT}/${NET}/v3.4}       # output directory
    export COMOUT=${COMOUT:-${COMROOT}/${NET}/v3.4/${RUN}.${PDY}}  # output directory
fi


export COMOUTcorms=${COMOUTcorms:-${COMOUTroot}/${RUN}.${PDY}}      # output directory
mkdir -m 775 -p $COMOUT $COMOUTcorms

####  Log File To Sys Report
##################################################################
export nosjlogfile=${COMOUT}/${PREFIXNOS}.jlogfile.${PDY}.${cycle}.log
####  Log File To COMOUTcorms
export cormslogfile=${COMOUT}/${PREFIXNOS}.corms.${PDY}.${cycle}.log

if [ -s $nosjlogfile ]; then
  cp -p $nosjlogfile $DATA/.
fi
if [ -s $cormslogfile ]; then
  cp -p $cormslogfile $DATA/.
fi
#export nosjlogfile=${DATA}/${PREFIXNOS}.jlogfile.${PDY}.${cycle}.log
####  Log File To COMOUTcorms
#export cormslogfile=${DATA}/${PREFIXNOS}.corms.${PDY}.${cycle}.log
env

#prod_name="`cat /etc/prod | cut -c1-1`"
#host="`hostname |  cut -c1-1`"
#if [ prod_name == $host ]; then
# tarfile=${OFS}.${PDY}${cyc}.${envir}.tar
#else
# tarfile=${OFS}.${PDY}${cyc}.tar
#if
#if [ $envir != prod ]; then
#  tarfile=${OFS}.${PDY}${cyc}.tar
#else
#  tarfile=${OFS}.${PDY}${cyc}.${envir}.tar
#   tarfile=${OFS}.${PDY}${cyc}.${envir}.wcoss2.tar
#fi
tarfile=${OFS}.${PDY}${cyc}.${envir}.wcoss2.tar
########################################################
# Execute the script.
########################################################
#   echo "push model data to CO-OPS ftp server of tidepool"
  $HOMEnos/ush/nos_ofs_aws_wcoss.sh
########################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$nosjlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
#cd $DATA_IN
#rm -rf ${DATA}

if [ $envir == 'dev' ]; then
  RPTDIR=/lfs/h1/nos/ptmp/$LOGNAME/rpt/${nosofs_ver}
  cp -p ${RPTDIR}/${OFS}_aws_${cyc}.out ${RPTDIR}/${OFS}_aws_${cyc}.out.${pbsid}
  cp -p ${RPTDIR}/${OFS}_aws_${cyc}.err ${RPTDIR}/${OFS}_aws_${cyc}.err.${pbsid}
elif [ $envir == 'prod' ]; then
  RPTDIR=/lfs/h1/nos/ptmp/$LOGNAME/rpt/${nosofs_ver}
  cp -p ${RPTDIR}/${OFS}_aws_${cyc}_prod.out ${RPTDIR}/${OFS}_aws_${cyc}_prod.out.${pbsid}
  cp -p ${RPTDIR}/${OFS}_aws_${cyc}_prod.err ${RPTDIR}/${OFS}_aws_${cyc}_prod.err.${pbsid}
fi

date



